// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcvaowanalqpcguchlvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjdmFvd2FuYWxxcGNndWNobHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MjQzNTYsImV4cCI6MjA3NDIwMDM1Nn0.pEWt0hrqlI2gPICMQJ4tpvVj2fCxp21n001L8rUU2iA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});